### ISSUE TITLE
release-gitter fails to build when /tmp/ and wheel build location are on separate mounts

### ISSUE THREAD

**Issue by rocode** [IamTheFij/release-gitter#2]
release-gitter fails to build when `/tmp/` and the wheel build location are on separate mounts.

Error log:
```
          × Building wheel for pseudo (pyproject.toml) did not run successfully.
          │ exit code: 1
          ╰─> [12 lines of output]
              Traceback (most recent call last):
                File "/pc/clone/QS-gDmx1QpG9ZloEk2_gYA/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
                  main()
                File "/pc/clone/QS-gDmx1QpG9ZloEk2_gYA/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
                  json_out['return_val'] = hook(**hook_input['kwargs'])
                File "/pc/clone/QS-gDmx1QpG9ZloEk2_gYA/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
                  return _build_backend().build_wheel(wheel_directory, config_settings,
                File "/tmp/pip-build-env-laqw7jdm/overlay/lib/python3.10/site-packages/pseudo_builder.py", line 132, in build_wheel
                  file.rename(wheel_scripts / file.name)
                File "/usr/lib/python3.10/pathlib.py", line 1232, in rename
                  self._accessor.rename(self, target)
              OSError: [Errno 18] Invalid cross-device link: '/pc/clone/QS-gDmx1QpG9ZloEk2_gYA/stylua' -> '/tmp/pip-wheel-rfs4j2kd/pseudo-0.13.1.data/scripts/stylua'
              [end of output]
 ```
REF: https://github.com/pre-commit-ci/issues/issues/132#issuecomment-1171503794

**Comment by IamTheFij** [comment]
Resolved in v1.1.1 via https://github.com/IamTheFij/release-gitter/commit/1b74126494509f78d924f98116208183dd6bfc39
