### ISSUE TITLE
pre-commit setup failure: KeyError: 'git-url'

### ISSUE THREAD

**Issue by rouge8** [IamTheFij/release-gitter#3]
I think version 2.2.0 is broken with pre-commit: https://github.com/JohnnyMorganz/StyLua/issues/807

### version information

```
pre-commit version: 3.5.0
git --version: git version 2.42.0
sys.version:
    3.12.0 (main, Oct  5 2023, 15:44:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/andy/.cache/pre-commit/repoaq7wm0_k
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Prepare meta /private/var/folders/yk/mvkbk1yd7652z8mxg76fyplm0000gn/T/pip-modern-metadata-_ivjttzi None
          Traceback (most recent call last):
            File "/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/yk/mvkbk1yd7652z8mxg76fyplm0000gn/T/pip-build-env-0n315rrm/overlay/lib/python3.12/site-packages/pseudo_builder.py", line 104, in prepare_metadata_for_build_wheel
              metadata = read_metadata()
                         ^^^^^^^^^^^^^^^
            File "/private/var/folders/yk/mvkbk1yd7652z8mxg76fyplm0000gn/T/pip-build-env-0n315rrm/overlay/lib/python3.12/site-packages/pseudo_builder.py", line 68, in read_metadata
              git_url = config.pop("git-url")
                        ^^^^^^^^^^^^^^^^^^^^^
          KeyError: 'git-url'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/opt/homebrew/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/andy/.cache/pre-commit/repoaq7wm0_k
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Prepare meta /private/var/folders/yk/mvkbk1yd7652z8mxg76fyplm0000gn/T/pip-modern-metadata-_ivjttzi None
          Traceback (most recent call last):
            File "/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/andy/.cache/pre-commit/repoaq7wm0_k/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/yk/mvkbk1yd7652z8mxg76fyplm0000gn/T/pip-build-env-0n315rrm/overlay/lib/python3.12/site-packages/pseudo_builder.py", line 104, in prepare_metadata_for_build_wheel
              metadata = read_metadata()
                         ^^^^^^^^^^^^^^^
            File "/private/var/folders/yk/mvkbk1yd7652z8mxg76fyplm0000gn/T/pip-build-env-0n315rrm/overlay/lib/python3.12/site-packages/pseudo_builder.py", line 68, in read_metadata
              git_url = config.pop("git-url")
                        ^^^^^^^^^^^^^^^^^^^^^
          KeyError: 'git-url'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

**Comment by rouge8** [comment]
Oh I see the issue -- it's a config option missing in StyLua

**Comment by sblask** [comment]
The readme makes as sound as if it should be optional though?

**Comment by IamTheFij** [comment]
You're right. This is a bug. In my latest change I must have accidentally made it required. I'll fix that and release a new version.

**Comment by IamTheFij** [comment]
Pushed 2.2.1 to build. Should be built and deployed soon. Thanks for reporting!
